services:
    _instanceof:
        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]

    _defaults:
        autowire: true
        autoconfigure: true

    Trilobit\RefreshBundle\Maintenance\RefreshMaintenance:
        public: true
        arguments:
            - '@contao.framework'
            - '@logger'
